--- #YAML:1.0
name:                POE-Component-Client-Traceroute
version:             0.11
abstract:            POE component for non-blocking/concurrent traceroutes.
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.30_01
author:              Andrew Hoying <ahoying@cpan.org>
distribution_type:   module
requires:     
    Net::RawIP:                    0.02
    POE:                           0.11
    Time::HiRes:                   1.2
meta-spec:
    url: <http://module-build.sourceforge.net/META-spec-new.html>;
    version: 1.1
